source geonamessrc
{
type = pgsql
sql_host = localhost
sql_user = geouser
sql_pass = geopw
sql_db = geonames
# TODO filter out lakes and other non-cities
sql_query = SELECT geoname.geonameid, geoname.name, geoname.alternatenames, geoname.population AS population FROM geoname
sql_attr_uint = population
}

index geonames
{
	source			= geonamessrc
	path			= /var/lib/sphinxsearch/data/geonames
	docinfo			= extern
	morphology			= none
	stopwords			=
	min_word_len		= 2
	charset_type		= sbcs
	min_prefix_len		= 0
	min_infix_len		= 0
}
searchd
{
port = 3312
log					= /var/log/sphinxsearch/searchd.log
query_log			= /var/log/sphinxsearch/query.log
read_timeout		= 5
max_children		= 30
pid_file			= /var/run/searchd.pid
max_matches			= 1000
seamless_rotate		= 1
preopen_indexes		= 0
unlink_old			= 1
}
